# Generated by Django 5.1.4 on 2025-01-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('BIOGRAPHY', 'Biography'), ('DRAMA', 'Drama'), ('SCI_FI', 'Sci Fi'), ('ROMANCE', 'Romance'), ('THRILLER', 'Thriller'), ('COMEDY', 'Comedy')], max_length=10),
        ),
    ]
