# Generated by Django 5.1.4 on 2025-01-16 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='year_of_release',
            field=models.IntegerField(default=1990, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
            preserve_default=False,
        ),
    ]
