# Generated by Django 5.1.4 on 2025-01-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.review'),
        ),
    ]
