# Generated by Django 5.1.4 on 2025-01-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_of_birth',
        ),
    ]
